### ISSUE TITLE
great tool

### ISSUE THREAD

**Issue by fate8383** [JanisV/release-bot#15]
this is exactly what I was looking for, thanks for it. I have a question. used git token and telegram token with chat IP. assuming this is private as it gets. What is the port 5000 is used for? I cannot seem to find that?

**Comment by fate8383** [comment]
using docker compose on arm

**Comment by JanisV** [comment]
Port 5000 is a server port for incoming requests from the Telegram (look at SITE_URL parameter) and should be proxed via nginx (when needed)

**Comment by fate8383** [comment]
> Port 5000 is a server port for incoming requests from the Telegram (look at SITE_URL parameter) and should be proxed via nginx (when needed)

not using site url, does it mean I do not need this open at all? I currently expose in docker rather than port, so it is kind of isolated in the docker network. still working, that's where I am confused do I really need this at al or not?

**Comment by JanisV** [comment]
> > Port 5000 is a server port for incoming requests from the Telegram (look at SITE_URL parameter) and should be proxed via nginx (when needed)
> 
> not using site url, does it mean I do not need this open at all? I currently expose in docker rather than port, so it is kind of isolated in the docker network. still working, that's where I am confused do I really need this at al or not?

In your case this port is not needed.
