### ISSUE TITLE
ARM support and instructions about bot owner

### ISSUE THREAD

**Issue by phampyk** [JanisV/release-bot#2]
Hello!! I just gave it a go after seeing this on reddit, but there's no instructions about letting the bot know the ID of the owner. Also would be great if it has ARM support, so it can be installed in raspberrypi and other ARM devices.

Would it be possible too to let the bot only be used by specific users, or just the owner, as to not be public? 

Thank you so much for your work!

**Comment by JanisV** [comment]
Added Docker image for arm64

**Comment by phampyk** [comment]
Thank you! I'll try it later on the raspberry pi.

Any documentation on how to tell the bot the owners id? Is it an env variable on the docker compose? Or is not implemented yet?

Thank you!

**Comment by JanisV** [comment]
Private bot planned for release 0.5
