### ISSUE TITLE
rate limit exceeded

### ISSUE THREAD

**Issue by giannis371** [JanisV/release-bot#3]
After adding around 20 repos im getting this error

Request GET /repos/hoarder-app/hoarder/releases/latest failed with 403: rate limit exceeded
release-bot  | Setting next backoff to 1475.239298s

**Comment by JanisV** [comment]
Look at GITHUB_TOKEN at https://github.com/JanisV/release-bot?tab=readme-ov-file#set-the-necessary-env-vars
